#!/bin/sh

cd `dirname $0`

PIDFILE=chessd.pid
LOGFILE=chessd.log
PYTHON="/usr/bin/env python"
TWISTD="$PYTHON /usr/bin/twistd"

case "$1" in
  start)
    echo "Starting chessd...."
    $TWISTD --logfile $LOGFILE --pidfile $PIDFILE -oy src/chessd.tac
    ;;
  run)
    echo "Running chessd in the foreground...."
    $TWISTD --pidfile $PIDFILE -noy src/chessd.tac
    ;;
  firstrun)
    $0 stop
    DB_DB=chess
    echo "Creating database..."
    mysql $DB_DB < db/db.sql
    echo "Loading ECO data..."
    python ./scripts/import-eco.py
    python ./scripts/headadmin.py
    ;;
  test)
    echo "Running test suite...."
    trial -e test/
    ;;
  check)
    echo "Running code checks...."
    ./scripts/check
    ./scripts/pep8
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  pull)
    echo "Pulling latest changes (but not restarting server)...."
    hg pull
    hg update -C
    ;;
  upgrade)
    echo "Upgrading and restarting server...."
    $0 stop
    hg pull
    hg update -C
    $0 start
    ;;
  reloaddb)
    echo "Reloading database...."
    mysql chess < db/db.sql
    ./scripts/import-eco.py
    ;;
  log)
    echo "Showing chessd log..."
    tail -100 $LOGFILE
    ;;
  profile)
    echo "Running chessd in profile mode...."
    $TWISTD --logfile $LOGFILE --profile profile-chessd.data --savestats --profiler cProfile -noy src/chessd.tac
    ;;
  stop)
    if [ -f $PIDFILE ]; then
      echo "Stopping chessd...."
      kill `cat $PIDFILE`
    else
      echo "Chessd does not appear to be running...."
    fi
    ;;
  *)
    echo "Usage: $0 (start|stop|run|test|profile|upgrade|reloaddb|log|restart|pull)"
    ;;
esac

